(function () {
  const extensionApi = typeof browser !== "undefined" ? browser : chrome;
  let aiSearchContainer = null;

  function getCurrentNid() {
    const parts = window.location.pathname.split("/");
    return parts.length > 2 ? parts[2] : null;
  }

  function rememberCurrentNid() {
    const nid = getCurrentNid();
    if (nid) {
      try {
        const result = extensionApi.storage.local.set({ lastNid: nid });
        if (result && typeof result.then === "function") {
          result.catch(() => {});
        }
      } catch (_) {}
    }
    return nid;
  }

  function getStoredTopK() {
    const result = extensionApi.storage.local.get(["topK"]);
    if (result && typeof result.then === "function") {
      return result;
    }
    return new Promise((resolve) => extensionApi.storage.local.get(["topK"], resolve));
  }

  function sendExtensionMessage(message) {
    const result = extensionApi.runtime.sendMessage(message);
    if (result && typeof result.then === "function") {
      return result;
    }
    return new Promise((resolve) => extensionApi.runtime.sendMessage(message, resolve));
  }

  function injectAiSearch() {
    if (document.getElementById("piazza-ai-search-btn")) return;

    // Use the confirmed ID for the search bar container
    const searchBar = document.getElementById("feed_search_bar");
    if (!searchBar) return;

    const btn = document.createElement("button");
    btn.id = "piazza-ai-search-btn";
    btn.innerText = "AI Search";
    btn.className = "btn btn-primary btn-sm";
    btn.style.marginLeft = "10px";
    btn.style.verticalAlign = "middle";

    btn.onclick = (e) => {
      e.preventDefault();
      const input = searchBar.querySelector("input");
      const query = input ? input.value.trim() : "";

      if (query) {
        performAiSearch(query);
      } else {
        alert("Please enter a search query in the search bar first.");
      }
    };

    searchBar.appendChild(btn);
  }

  async function performAiSearch(query) {
    const nid = rememberCurrentNid();
    if (!nid) {
      alert("Could not determine class ID. Are you on a class page?");
      return;
    }

    const stored = await getStoredTopK();
    const parsedTopK = Number(stored.topK);
    const topK = parsedTopK > 0 ? parsedTopK : undefined;

    showResultsOverlay();
    setOverlayStatus("Searching Piazza and generating AI answer...");

    sendExtensionMessage({
      type: "AI_SEARCH",
      payload: { query, nid, topK },
    })
      .then((response) => {
        if (response && response.error) {
          setOverlayError(response.error);
        } else {
          displayResults(response);
        }
      })
      .catch((error) => {
        setOverlayError(error && error.message ? error.message : String(error));
      });
  }

  function showResultsOverlay() {
    if (aiSearchContainer) aiSearchContainer.remove();

    aiSearchContainer = document.createElement("div");
    aiSearchContainer.id = "piazza-ai-results-overlay";
    aiSearchContainer.innerHTML = `
      <div class="piazza-ai-header">
        <h3>AI Search Results</h3>
        <button id="piazza-ai-close">&times;</button>
      </div>
      <div id="piazza-ai-content">
        <div class="piazza-ai-status"></div>
      </div>
    `;
    document.body.appendChild(aiSearchContainer);

    document.getElementById("piazza-ai-close").onclick = () => {
      aiSearchContainer.remove();
      aiSearchContainer = null;
    };
  }

  function setOverlayStatus(status) {
    const content = document.getElementById("piazza-ai-content");
    if (content) {
      content.innerHTML = `<div class="piazza-ai-status">${status}</div>`;
    }
  }

  function setOverlayError(error) {
    const content = document.getElementById("piazza-ai-content");
    if (content) {
      content.innerHTML = `<div class="piazza-ai-error">Error: ${error}</div>`;
    }
  }

  function displayResults(data) {
    const content = document.getElementById("piazza-ai-content");
    if (!content) return;

    if (!data || !data.answer) {
      setOverlayError("No response received from the background worker.");
      return;
    }

    const sources = Array.isArray(data.sources) ? data.sources : [];
    let sourcesHtml = sources
      .map(
        (s) => `
      <li><a href="${s.url}" target="_blank">${s.subject}</a></li>
    `
      )
      .join("");

    const meta =
      data.meta && data.meta.provider && data.meta.model
        ? `<div class="piazza-ai-meta">Generated by ${data.meta.provider} (${data.meta.model})</div>`
        : "";

    content.innerHTML = `
      <div class="piazza-ai-answer">${String(data.answer).replace(/\n/g, "<br>")}</div>
      ${
        sources.length
          ? `
      <div class="piazza-ai-sources">
        <h4>Sources:</h4>
        <ul>${sourcesHtml}</ul>
      </div>`
          : ""
      }
      ${meta}
    `;
  }

  // Watch for DOM changes to inject the button
  const observer = new MutationObserver(() => {
    injectAiSearch();
  });

  observer.observe(document.body, { childList: true, subtree: true });
  injectAiSearch();
  rememberCurrentNid();
})();
